name: SimpleFreeze
main: io.github.Prxmium.SimpleFreeze.SimpleFreeze
version: 1.1

commands:
   freeze:
        description: Freeze other players.
        default: op
        permission: sf.freeze
        permission-message: You don't have permission!
   warn:
        description: Turn off warning.
        default: op
        permission: sf.warn
        permission-message: You don't have permission!