main: main.Main
name: SimpleFreeze
version: 1.5.1
commands:
  freeze:
    description: Freezes/Unfreezes player.
    permission: sf.freeze
    usage: /freeze <player>
  frozenplayers:
    description: Lists frozen players.
    permissions: sf.list
