main: main.Main
name: SimpleFreeze
version: 1.5
commands:
  freeze:
    description: Freezes the player.
    permission: sf.freeze
    usage: /freeze <player>
  unfreeze:
    description: Unfreezes the player.
    permission: sf.freeze
    usage: /unfreeze <player>
  frozenplayers:
    description: Lists frozen players.
    permissions: sf.list
