main: prxmium.simplefreeze.Main
name: SimpleFreeze
version: 1.4.3
commands:
  freeze:
    description: Freezes the player.
    permission: sf.freeze
    usage: /freeze <player>
  unfreeze:
    description: Unfreezes the player.
    permission: sf.freeze
    usage: /unfreeze <player>
